Repository winsw/winsw, pull requests merged in 2019-08, with the labels that each got.

#330 Fix duplicate startup logging
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
Labels: bug

#321 Add a new `hidewindow` option to suppress windows popup on legacy platforms
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
Labels: enhancement

#315 Prevent application crash when `roll-by-size-time` is enabled
  src/Core/WinSWCore/LogAppenders.cs
Labels: bug

#331 Add Release Drafter configuration to automate changelogs
  .github/release-drafter.yml
Labels: internal

#332 Move Maven packaging to https://github.com/jenkinsci/winsw-maven-packaging
  DEVELOPER.md
  pom.xml
Labels: build-flow
