Repository winsw/winsw, pull requests merged in 2020-01, with the labels that each got.

#358 Add CODEOWNERS to automate code review requests
  .github/CODEOWNERS
Labels: internal

#352 Migrate to SDK-style projects + Require Visual Studio Community 2019 to build the project
  .gitignore
  DEVELOPER.md
  Directory.Build.props
  WinSW.nuspec
  appveyor.yml
  generate-key.ps1
  sign.sh
  src/.nuget/NuGet.Config
  src/.nuget/NuGet.exe
  src/.nuget/NuGet.targets
  src/.nuget/packages.config
  src/Core/ServiceWrapper/Properties/AssemblyInfo.cs
  src/Core/ServiceWrapper/packages.config
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/ServiceWrapper_dotNET4/Main.cs
  src/Core/ServiceWrapper_dotNET4/Properties/AssemblyInfo.cs
  src/Core/ServiceWrapper_dotNET4/packages.config
  src/Core/ServiceWrapper_dotNET4/winsw_dotNET4.csproj
  src/Core/WinSWCore/Properties/AssemblyInfo.cs
  src/Core/WinSWCore/WinSWCore.csproj
  src/Core/WinSWCore/packages.config
  src/Plugins/RunawayProcessKiller/Properties/AssemblyInfo.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/RunawayProcessKiller/packages.config
  src/Plugins/SharedDirectoryMapper/Properties/AssemblyInfo.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
  src/Plugins/SharedDirectoryMapper/packages.config
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/NunitTest.nunit
  src/Test/winswTests/Properties/AssemblyInfo.cs
  src/Test/winswTests/Util/ProcessHelperTest.cs
  src/Test/winswTests/packages.config
  src/Test/winswTests/winswTests.csproj
  src/packages/repositories.config
  src/winsw.sln
  winsw.csproj
Labels: internal

#353 Code Style and Formatting cleanup
  src/Core/ServiceWrapper/Logging/WrapperServiceEventLogProvider.cs
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/SigIntHelper.cs
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/Download.cs
  src/Core/WinSWCore/DynamicProxy.cs
  src/Core/WinSWCore/Extensions/AbstractWinSWExtension.cs
  src/Core/WinSWCore/Extensions/ExtensionException.cs
  src/Core/WinSWCore/Extensions/ExtensionPointAttribute.cs
  src/Core/WinSWCore/Extensions/IWinSWExtension.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionDescriptor.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
  src/Core/WinSWCore/LogAppenders.cs
  src/Core/WinSWCore/Logging/IServiceEventLogProvider.cs
  src/Core/WinSWCore/Logging/ServiceEventLogAppender.cs
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/Native/Kernel32.cs
  src/Core/WinSWCore/PeriodicRollingCalendar.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
  src/Core/WinSWCore/Util/SigIntHelper.cs
  src/Core/WinSWCore/Util/XmlHelper.cs
  src/Core/WinSWCore/WinSWException.cs
  src/Core/WinSWCore/WinSWSystem.cs
  src/Core/WinSWCore/Wmi.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperConfig.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperHelper.cs
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/DownloadTest.cs
  src/Test/winswTests/Extensions/ExtensionTestBase.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs
  src/Test/winswTests/MainTest.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/CLITestHelper.cs
  src/Test/winswTests/Util/ConfigXmlBuilder.cs
  src/Test/winswTests/Util/ExceptionHelper.cs
  src/Test/winswTests/Util/FilesystemTestHelper.cs
  src/Test/winswTests/Util/ProcessHelperTest.cs
  src/Test/winswTests/Util/ServiceDescriptorAssert.cs
Labels: invalid

#354 Add new target frameworks: .NET 4.5, .NET Core win-x64, .NET Core win-x86 + Fix archiving of old logs in the `roll-by-size-time` mode
  Directory.Build.targets
  appveyor.yml
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/WinSWCore/DynamicProxy.cs
  src/Core/WinSWCore/LogAppenders.cs
  src/Core/WinSWCore/WinSWCore.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/NunitTest.nunit
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/CLITestHelper.cs
  src/Test/winswTests/Util/ExceptionHelper.cs
  src/Test/winswTests/winswTests.csproj
Labels: bug, enhancement

#363 Target .NET Framework 4.6.1 instead of 4.5
  Directory.Build.targets
  appveyor.yml
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/WinSWCore/WinSWCore.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
  src/Test/winswTests/winswTests.csproj
Labels: enhancement

#356 Annotate for nullable reference types
  src/Core/ServiceWrapper/Logging/WrapperServiceEventLogProvider.cs
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/NullableAttributes.cs
  src/Core/ServiceWrapper/SigIntHelper.cs
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/Download.cs
  src/Core/WinSWCore/DynamicProxy.cs
  src/Core/WinSWCore/Extensions/AbstractWinSWExtension.cs
  src/Core/WinSWCore/Extensions/IWinSWExtension.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionDescriptor.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
  src/Core/WinSWCore/LogAppenders.cs
  src/Core/WinSWCore/Logging/IServiceEventLogProvider.cs
  src/Core/WinSWCore/Logging/ServiceEventLogAppender.cs
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/Native/Kernel32.cs
  src/Core/WinSWCore/NullableAttributes.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
  src/Core/WinSWCore/Util/SigIntHelper.cs
  src/Core/WinSWCore/Util/XmlHelper.cs
  src/Core/WinSWCore/WinSWCore.csproj
  src/Core/WinSWCore/Wmi.cs
  src/Core/WinSWCore/WmiSchema.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
Labels: internal

#360 Simplify syntax
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/LogAppenders.cs
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/PeriodicRollingCalendar.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperConfig.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperHelper.cs
  src/Test/winswTests/DownloadTest.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/CLITestHelper.cs
  src/Test/winswTests/Util/ConfigXmlBuilder.cs
  src/Test/winswTests/Util/ExceptionHelper.cs
  src/Test/winswTests/Util/ProcessHelperTest.cs
  src/Test/winswTests/winswTests.csproj
Labels: internal

#369 Fix configuration samples
  examples/sample-allOptions.xml
  examples/sample-minimal.xml
Labels: documentation

#377 Disable Nuget account and project feeds to fix CI
  appveyor.yml
Labels: internal

#380 Fix the release flow after packaging changes
  appveyor-release.yml
Labels: internal

#381 Fix file extensions for .NET Core artifacts
  appveyor.yml
Labels: internal, skip-changelog

#389 Fix executable path and XML config file resolution on .NET Core
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
Labels: bug

#359 Fix RunawayProcessKiller
  src/Plugins/RunawayProcessKiller/NativeMethods.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
Labels: bug

#383 Produce ready-to-publish artifacts in build phase for AppVeyor
  .gitignore
  Directory.Build.props
  WinSW.nuspec
  appveyor.yml
  src/Core/ServiceWrapper/winsw.csproj
Labels: internal

#390 Stop buffering stdout/stderr
  src/Core/WinSWCore/LogAppenders.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
Labels: enhancement

#373 Don't print stack trace to console for user errors
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
Labels: enhancement
