Repository winsw/winsw, pull requests merged in 2020-05, with the labels that each got.

#528 Support proxy attribute for download
  doc/xmlConfigFile.md
  src/Core/WinSWCore/Download.cs
  src/Test/winswTests/DownloadTest.cs
Labels: new-feature

#531 Increase code coverage
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/Properties/AssemblyInfo.cs
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/DownloadConfigTests.cs
  src/Test/winswTests/DownloadTests.cs
  src/Test/winswTests/MainTest.cs
  src/Test/winswTests/Util/AsyncAssert.cs
  src/Test/winswTests/Util/DateTimeExtensions.cs
  src/Test/winswTests/Util/TestHelper.cs
Labels: tests

#532 Support <startarguments> and <stoparguments>
  doc/xmlConfigFile.md
  examples/sample-allOptions.xml
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
Labels: bug

#417 Properly request additional time for shutdown when `<waithint>` is set
  src/Core/ServiceWrapper/Main.cs
Labels: bug

#341 Add stopwait command - same as stop, but waits until the service is actually stopped:
  README.md
  src/Core/ServiceWrapper/Main.cs
Labels: enhancement

#513 Reorganize interop codes
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/AssemblyInfo.cs
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/Native/ConsoleApis.cs
  src/Core/WinSWCore/Native/Errors.cs
  src/Core/WinSWCore/Native/HandleApis.cs
  src/Core/WinSWCore/Native/Kernel32.cs
  src/Core/WinSWCore/Native/Libraries.cs
  src/Core/WinSWCore/Native/ProcessApis.cs
  src/Core/WinSWCore/Native/Security.cs
  src/Core/WinSWCore/Native/SecurityApis.cs
  src/Core/WinSWCore/Native/Service.cs
  src/Core/WinSWCore/Native/ServiceApis.cs
  src/Core/WinSWCore/Native/Throw.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/Util/SigIntHelper.cs
  src/Core/WinSWCore/WinSWCore.csproj
Labels: internal

#534 Contributor guidelines: Document the project structure
  CONTRIBUTING.md
  doc/developer/projectStructure.md
Labels: documentation
