Repository winsw/winsw, pull requests merged in 2020-12, with the labels that each got.

#727 Rename self-contained deliverables
  eng/build.yml
  src/WinSW/WinSW.csproj
Labels: packaging

#728 Ensure basic event logging
  src/WinSW/Logging/IServiceEventLogProvider.cs
  src/WinSW/Logging/ServiceEventLogAppender.cs
  src/WinSW/Logging/WrapperServiceEventLogProvider.cs
  src/WinSW/Program.cs
Labels: enhancement

#729 Upgrade build flows
  Directory.Build.props
  Directory.Build.targets
  LICENSE.txt
  WinSW.nuspec
  eng/build.yml
  examples/sample-allOptions.xml
  examples/sample-minimal.xml
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Download.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Core/Util/FileHelper.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/Program.cs
  src/WinSW/WinSW.csproj
  src/WinSW/WrapperService.cs
Labels: build-flow, packaging

#730 Rename framework-dependent deliverables
  WinSW.nuspec
  eng/build.yml
  src/WinSW.Tests/Util/Layout.cs
  src/WinSW/WinSW.csproj
Labels: packaging

#735 Style updates
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Configuration/Log.cs
  src/WinSW.Core/Configuration/YamlConfiguration.cs
  src/WinSW.Core/Download.cs
  src/WinSW.Core/DynamicProxy.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Core/LogAppenders.cs
  src/WinSW.Core/Logging/ServiceEventLogAppender.cs
  src/WinSW.Core/Native/Security.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/Throw.cs
  src/WinSW.Core/PeriodicRollingCalendar.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Core/ServiceDescriptorYaml.cs
  src/WinSW.Core/Util/ConfigHelper.cs
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW.Core/Util/XmlHelper.cs
  src/WinSW.Core/Wmi.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Plugins/SharedDirectoryMapper.cs
  src/WinSW.Plugins/SharedDirectoryMapperHelper.cs
  src/WinSW.Tests/Configuration/ExamplesTest.cs
  src/WinSW.Tests/DownloadConfigTests.cs
  src/WinSW.Tests/DownloadTests.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW.Tests/Extensions/SharedDirectoryMapperTest.cs
  src/WinSW.Tests/MainTest.cs
  src/WinSW.Tests/ServiceDescriptorYamlTest.cs
  src/WinSW.Tests/Util/CLITestHelper.cs
  src/WinSW.Tests/Util/ConfigXmlBuilder.cs
  src/WinSW.Tests/Util/FilesystemTestHelper.cs
  src/WinSW.Tests/Util/ProcessHelperTest.cs
  src/WinSW.Tests/Util/ServiceDescriptorAssert.cs
  src/WinSW/Logging/WrapperServiceEventLogProvider.cs
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: internal

#736 Backport diagnosability updates
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: bug

#737 Backport process util updates
  src/WinSW.Core/Native/Libraries.cs
  src/WinSW.Core/Native/ProcessApis.cs
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW.Core/Util/SignalHelper.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW/WrapperService.cs
Labels: bug

#738 Leave STDIN open
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW/WrapperService.cs
Labels: bug

#731 Revise docs for 3.0.0-alpha.7
  README.md
  WinSW.nuspec
  docs/developer/project-structure.md
  docs/installation.md
  samples/complete.xml
  samples/jenkins.xml
  samples/minimal.xml
  samples/shared-directory-mapper.xml
  src/WinSW.Tests/Configuration/ExamplesTest.cs
Labels: documentation

#745 Update build.yml
  eng/build.yml
Labels: internal

#748 Update build.yml
  eng/build.yml
Labels: internal

#750 Update exception message
  src/WinSW.Core/Native/Throw.cs
Labels: enhancement, skip-changelog

#752 Set console output code page to UTF-8
  src/WinSW.Core/Native/ConsoleApis.cs
  src/WinSW/WrapperService.cs
Labels: bug

#753 Set console output code page to UTF-8
  src/WinSW.Core/Native/ConsoleApis.cs
  src/WinSW.Core/Util/ProcessHelper.cs
Labels: bug

#751 Backport command updates
  src/WinSW.Core/CommandException.cs
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Configuration/IWinSWConfiguration.cs
  src/WinSW.Core/Configuration/YamlConfiguration.cs
  src/WinSW.Core/DynamicProxy.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Core/Native/Errors.cs
  src/WinSW.Core/Native/Security.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW.Core/Native/Throw.cs
  src/WinSW.Core/NullableAttributes.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Core/ServiceDescriptorYaml.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Core/Wmi.cs
  src/WinSW.Core/WmiSchema.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Tests/Configuration/ExamplesTest.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW.Tests/ServiceDescriptorTests.cs
  src/WinSW.Tests/ServiceDescriptorYamlTest.cs
  src/WinSW.Tests/Util/ServiceDescriptorAssert.cs
  src/WinSW/FormatExtensions.cs
  src/WinSW/Program.cs
  src/WinSW/ServiceControllerExtension.cs
  src/WinSW/WinSW.csproj
  src/WinSW/WrapperService.cs
Labels: enhancement

#754 Bump log4net to 2.0.12
  src/WinSW.Core/Native/Throw.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW/Program.cs
  src/WinSW/WinSW.csproj
  src/WinSW/WrapperService.cs
Labels: dependencies

#755 Backport logging updates
  src/WinSW.Core/Logging/IServiceEventLogProvider.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Core/ServiceDescriptorYaml.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW/Logging/ServiceEventLogAppender.cs
  src/WinSW/Logging/WrapperServiceEventLogProvider.cs
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: enhancement

#757 Internal updates
  src/WinSW.Core/Native/Service.cs
  src/WinSW/Program.cs
Labels: internal

#758 Enhance console prompting
  src/WinSW.Core/Native/ConsoleApis.cs
  src/WinSW.Core/Native/ConsoleEx.cs
  src/WinSW.Core/Native/Credentials.cs
  src/WinSW.Core/Native/FileApis.cs
  src/WinSW.Core/Native/Handle.cs
  src/WinSW.Core/Native/ProcessApis.cs
  src/WinSW.Core/Native/Security.cs
  src/WinSW.Tasks/Trim.cs
  src/WinSW/Program.cs
  src/WinSW/WinSW.csproj
Labels: enhancement

#759 Enhance console prompting
  src/WinSW.Core/Native/ConsoleApis.cs
  src/WinSW.Core/Native/ConsoleEx.cs
  src/WinSW.Core/Native/Credentials.cs
  src/WinSW.Core/Native/FileApis.cs
  src/WinSW.Core/Native/Handle.cs
  src/WinSW.Core/Native/ProcessApis.cs
  src/WinSW.Core/Native/Security.cs
  src/WinSW/Program.cs
Labels: enhancement

#678 Fix inconsistencies in YAML config
  doc/yamlConfigurationSchema.json
  examples/sample-allOption.yml
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Configuration/ServiceAccount.cs
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Configuration/YamlServiceConfig.cs
  src/WinSW.Core/Configuration/YamlServiceConfigLoader.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Plugins/SharedDirectoryMapper.cs
  src/WinSW.Plugins/SharedDirectoryMapperConfig.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW.Tests/Extensions/SharedDirectoryMapperTest.cs
  src/WinSW.Tests/ServiceDescriptorTests.cs
  src/WinSW.Tests/ServiceDescriptorYamlTest.cs
  src/WinSW.Tests/Util/ConfigXmlBuilder.cs
  src/WinSW/Program.cs
Labels: bug

#761 Allow rotating logs monthly
  src/WinSW.Core/PeriodicRollingCalendar.cs
Labels: bug

#760 Save credentials
  src/WinSW.Core/Native/ConsoleEx.cs
  src/WinSW.Core/Native/CredentialApis.cs
  src/WinSW.Core/Native/Credentials.cs
  src/WinSW.Core/Native/FileTime.cs
  src/WinSW.Core/Native/RegistryApis.cs
  src/WinSW.Core/Util/RegistryKeyExtensions.cs
  src/WinSW/Program.cs
Labels: enhancement

#763 Make release drafter run manually
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/changelog-management.yml
Labels: internal

#764 Remove test command
  README.md
  docs/cli-commands.md
  src/WinSW/Program.cs
Labels: removed

#765 Rework Shared Directory Mapper
  src/WinSW.Plugins/SharedDirectoryMapper.cs
  src/WinSW.Plugins/SharedDirectoryMapperConfig.cs
  src/WinSW.Plugins/SharedDirectoryMapperHelper.cs
  src/WinSW.Tests/Extensions/SharedDirectoryMapperConfigTest.cs
  src/WinSW.Tests/Extensions/SharedDirectoryMapperTests.cs
Labels: enhancement
