Repository winsw/winsw, pull requests merged in 2020-03, with the labels that each got.

#428 Use StringBuilder
  src/Core/WinSWCore/Wmi.cs
Labels: internal

#430 Use generic enum parsing methods in all packages except .NET 2.0
  src/Core/WinSWCore/Util/XmlHelper.cs
Labels: internal

#441 Update license for GitHub
  LICENSE.txt
Labels: internal

#443 Fix NuGet warning
  WinSW.nuspec
Labels: internal

#450 Add a Gitter chat for the project
  README.md
Labels: internal

#448 Update the repository locations in Documentation and the NuGet spec
  CHANGELOG.md
  README.md
  WinSW.nuspec
Labels: documentation

#403 Support 'If-Modified-Since' for downloads
  src/Core/WinSWCore/Download.cs
Labels: enhancement

#452 Add .NET 4.6.1 executables to the NuGet package
  WinSW.nuspec
Labels: enhancement

#362 Improve P/Invoke signatures
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/SigIntHelper.cs
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/Native/Kernel32.cs
  src/Core/WinSWCore/Util/SigIntHelper.cs
Labels: internal

#449 Introduce a new winsw organization on AppVeyor, move CI there
  DEVELOPER.md
  README.md
Labels: internal

#357 Optimize DynamicProxy
  src/Core/WinSWCore/DynamicProxy.cs
  src/Core/WinSWCore/Wmi.cs
Labels: internal

#431 Support security descriptor string
  doc/xmlConfigFile.md
  examples/sample-allOptions.xml
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/WinSWCore.csproj
Labels: new-feature

#392 Set description via advapi32
  src/Core/ServiceWrapper/Main.cs
  src/Core/WinSWCore/Native/Advapi32.cs
Labels: enhancement

#459 Initialize contributing guidelines
  CONTRIBUTING.md
  DEVELOPER.md
Labels: documentation

#456 Create Issue templates
  .github/ISSUE_TEMPLATE/1-feature-request.md
  .github/ISSUE_TEMPLATE/2-bug-report.md
  .github/ISSUE_TEMPLATE/3-documentation.md
  .github/ISSUE_TEMPLATE/4-question.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: internal

#464 Fix default domain name
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
Labels: bug

#463 Annotate for NRT
  src/Core/WinSWCore/Util/XmlHelper.cs
Labels: internal
