Repository winsw/winsw, pull requests merged in 2020-09, with the labels that each got.

#676 Enable member-level trimming
  src/WinSW/WinSW.csproj
Labels: build-flow

#680 Fix service crashes
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW.Core/Util/SignalHelper.cs
  src/WinSW/WrapperService.cs
Labels: bug

#683 Fix code analysis warnings
  src/WinSW.Core/Configuration/ServiceConfig.cs
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Download.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Core/Util/XmlHelper.cs
  src/WinSW.Core/WinSWSystem.cs
Labels: internal

#675 Update YAML configuration documentation
  doc/yamlConfigFile.md
Labels: documentation

#686 Fix build warnings
  eng/build.yml
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/Util/InterProcessCodeCoverageSession.cs
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/WinSW.csproj
Labels: internal

#685 Add `dev ps -a|--all` option
  src/WinSW/Program.cs
Labels: new-feature

#688 Fix console logging
  src/WinSW/Logging/WinSWConsoleAppender.cs
Labels: bug
