Repository winsw/winsw, pull requests merged in 2020-08, with the labels that each got.

#617 Refactor service configuration
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Configuration/IWinSWConfiguration.cs
  src/WinSW.Core/Configuration/ServiceConfig.cs
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Extensions/AbstractWinSWExtension.cs
  src/WinSW.Core/Extensions/IWinSWExtension.cs
  src/WinSW.Core/Extensions/WinSWExtensionManager.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Plugins/SharedDirectoryMapper.cs
  src/WinSW.Tests/Configuration/ExamplesTest.cs
  src/WinSW.Tests/DownloadConfigTests.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW.Tests/Extensions/SharedDirectoryMapperConfigTest.cs
  src/WinSW.Tests/ServiceConfigTests.cs
  src/WinSW.Tests/Util/CommandLineTestHelper.cs
  src/WinSW.Tests/Util/ConfigXmlBuilder.cs
  src/WinSW.Tests/Util/ServiceConfigAssert.cs
  src/WinSW.Tests/Util/ServiceDescriptorAssert.cs
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: internal

#618 Ensure child processes are cleanup up
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Util/ProcessExtensions.cs
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW/WrapperService.cs
Labels: enhancement

#619 Handle special accounts
  src/WinSW.Core/Native/Security.cs
  src/WinSW.Core/Native/SecurityApis.cs
  src/WinSW/Program.cs
Labels: enhancement

#620 Add `dev ps` command
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW.Core/Util/ProcessExtensions.cs
  src/WinSW/Program.cs
Labels: new-feature

#621 Allow `<stopexecutable>` without arguments
  src/WinSW/WrapperService.cs
Labels: enhancement

#440 Remove Runaway Process Killer
  docs/extensions/extensions.md
  docs/extensions/runaway-process-killer.md
  samples/sample-runaway-process-killer.xml
  src/WinSW.Core/Native/JobApis.cs
  src/WinSW.Plugins/RunawayProcessKillerExtension.cs
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW.Tests/Util/ConfigXmlBuilder.cs
  src/WinSW/WrapperService.cs
Labels: removed

#622 Reduce event log entries
  src/WinSW.Core/LogAppenders.cs
  src/WinSW.Core/Util/ProcessExtensions.cs
  src/WinSW.Core/Util/SignalHelper.cs
  src/WinSW/WrapperService.cs
Labels: enhancement

#623 CLI updates
  src/WinSW.Core/Configuration/ServiceConfig.cs
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/FormatExtensions.cs
  src/WinSW.Core/Native/Errors.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW.Core/Native/Throw.cs
  src/WinSW.Core/NullableAttributes.cs
  src/WinSW.Tests/Configuration/ExamplesTest.cs
  src/WinSW.Tests/Util/CommandLineTestHelper.cs
  src/WinSW.Tests/Util/ServiceConfigAssert.cs
  src/WinSW/Logging/WinSWConsoleAppender.cs
  src/WinSW/NullableAttributes.cs
  src/WinSW/Program.cs
  src/WinSW/ServiceControllerExtension.cs
  src/WinSW/WrapperService.cs
Labels: enhancement

#625 Support sending `WM_CLOSE` message
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Util/ProcessExtensions.cs
  src/WinSW.Core/Util/SignalHelper.cs
  src/WinSW/WrapperService.cs
Labels: new-feature

#626 Console isolation
  src/WinSW.Core/Native/ConsoleApis.cs
  src/WinSW/WrapperService.cs
Labels: bug

#615 Add `customize` command
  src/WinSW.Core/Native/ResourceApis.cs
  src/WinSW.Core/Native/Resources.cs
  src/WinSW.Core/Native/Throw.cs
  src/WinSW.Tests/Configuration/ExamplesTest.cs
  src/WinSW.Tests/MainTest.cs
  src/WinSW.Tests/Util/Layout.cs
  src/WinSW/Program.cs
Labels: needs-review, new-feature

#569 Remove unnecessary project items
  src/Core/ServiceWrapper/winsw.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
  src/Test/winswTests/winswTests.csproj
Labels: build-flow

#580 Stop parent process first by default
  doc/extensions/runawayProcessKiller.md
  examples/sample-allOptions.xml
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Plugins/RunawayProcessKiller/sampleConfig.xml
  src/Test/winswTests/ServiceDescriptorTests.cs
Labels: bug

#582 Fix file length accumulation
  src/Core/WinSWCore/LogAppenders.cs
Labels: bug

#629 Update release Drafter to v5.11.0
  .github/workflows/changelog-management.yml
Labels: internal

#631 Add stdout/stderr path settings
  src/WinSW.Core/Configuration/ProcessCommand.cs
  src/WinSW.Core/Configuration/SettingNames.cs
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/LogAppenders.cs
  src/WinSW.Tests/ServiceConfigTests.cs
  src/WinSW/WrapperService.cs
Labels: new-feature

#632 Update .NET Framework packaging
  src/WinSW.Tasks/Trim.cs
  src/WinSW.Tasks/WinSW.Tasks.csproj
  src/WinSW.Tests/MetadataTests.cs
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW.sln
  src/WinSW/WinSW.csproj
Labels: build-flow

#635 Remove `--timeout` option
  src/WinSW/Program.cs
Labels: removed

#636 Fix path inconsistency
  src/WinSW.Core/Configuration/ServiceConfig.cs
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Tests/Util/CommandLineTestHelper.cs
  src/WinSW/Program.cs
Labels: bug

#639 Add `dev kill` command
  src/WinSW/Program.cs
Labels: new-feature

#642 Disable raising events
  src/WinSW/WrapperService.cs
Labels: bug

#643 Fix service crashes
  src/WinSW.Core/Util/ProcessExtensions.cs
  src/WinSW.Tests/CommandLineTests.cs
  src/WinSW/ServiceMessages.cs
  src/WinSW/WrapperService.cs
Labels: bug

#641 Support both XML and YAML configuration + Remove support for *.vshost files and folder hierarchy lookup which used to be an undocumented development features
  README.md
  src/Core/ServiceWrapper/Program.cs
  src/Core/ServiceWrapper/WrapperService.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/ServiceDescriptorYaml.cs
Labels: bug, removed

#608 Revise docs for 3.0.0-alpha.3
  CONTRIBUTING.md
  MANIFEST.md
  README.md
  docs/cli-commands.md
  docs/deferred-file-operations.md
  docs/extensions/extensions.md
  docs/extensions/shared-directory-mapper.md
  docs/installation.md
  docs/logging-and-error-reporting.md
  docs/migrate-to-3-x.md
  docs/self-restarting-service.md
  docs/xml-config-file.md
  samples/sample-complete.xml
  samples/sample-minimal.xml
  src/WinSW.Tests/ServiceConfigTests.cs
Labels: documentation

#644 Fix a case error in README.md
  doc/yamlConfigFile.md
Labels: documentation

#651 Upgrade to .NET 5
  eng/build.yml
  src/WinSW.Core/Configuration/ServiceConfig.cs
  src/WinSW.Core/Download.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/Program.cs
  src/WinSW/WinSW.csproj
  src/WinSW/WrapperService.cs
Labels: build-flow

#647 YAML config test coverage
  src/Core/WinSWCore/Configuration/YamlConfiguration.cs
  src/Test/winswTests/ServiceDescriptorYamlTest.cs
Labels: tests

#638 YAML support for extension
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/Configuration/YamlConfiguration.cs
  src/Core/WinSWCore/Configuration/YamlExtensionConfiguration.cs
  src/Core/WinSWCore/Extensions/AbstractWinSWExtension.cs
  src/Core/WinSWCore/Extensions/IWinSWExtension.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionDescriptor.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/ServiceDescriptorYaml.cs
  src/Core/WinSWCore/Util/ConfigHelper.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperConfig.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs
Labels: enhancement, squash-merge-me

#660 Fix installation crashes when `allowservicelogon` is `true`
  src/Core/WinSWCore/Native/Security.cs
  src/Core/WinSWCore/Native/SecurityApis.cs
Labels: bug

#663 Case-insensitive search for type name
  src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
Labels: bug

#656 JSON schema file for YAML configuration schema validation
  doc/yamlConfigFile.md
  doc/yamlConfigurationSchema.json
Labels: documentation, enhancement

#672 Add `dev list` command
  src/WinSW.Core/Native/Security.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Tests/Util/InterProcessCodeCoverageSession.cs
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: new-feature

#648 Auto refresh
  src/WinSW.Core/Configuration/XmlServiceConfig.cs
  src/WinSW.Core/Native/RegistryApis.cs
  src/WinSW.Core/Util/RegistryKeyExtensions.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW/Program.cs
Labels: new-feature

#673 Catch
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: enhancement

#645 Revise docs for 3.0.0-alpha.4
  .github/release-drafter.yml
  CONTRIBUTING.md
  README.md
  docs/cli-commands.md
  docs/xml-config-file.md
  eng/build.yml
Labels: documentation
