Repository winsw/winsw, pull requests merged in 2020-04, with the labels that each got.

#470 Issue templates: Fix the Documentation icon rendering
  .github/ISSUE_TEMPLATE/3-documentation.md
Labels: skip-changelog

#458 Clean up documentation, move changelog to GitHub releases
  CHANGELOG.md
  DEVELOPER.md
  MANIFEST.md
  README.md
  doc/deferredFileOperations.md
  doc/exeConfigFile.md
  doc/extensions/extensions.md
  doc/extensions/runawayProcessKiller.md
  doc/extensions/sharedDirectoryMapper.md
  doc/installation.md
  doc/loggingAndErrorReporting.md
  doc/selfRestartingService.md
  doc/xmlConfigFile.md
Labels: documentation

#473 Update documentation headers
  CHANGELOG.md
  README.md
  doc/deferredFileOperations.md
  doc/exeConfigFile.md
  doc/extensions/extensions.md
  doc/extensions/runawayProcessKiller.md
  doc/extensions/sharedDirectoryMapper.md
  doc/installation.md
  doc/loggingAndErrorReporting.md
  doc/selfRestartingService.md
  doc/xmlConfigFile.md
Labels: documentation

#476 Update .gitignore
  .gitignore
Labels: internal

#465 Split commands into functions
  src/Core/ServiceWrapper/Main.cs
  src/Test/winswTests/MainTest.cs
Labels: internal

#475 Update links
  README.md
  doc/installation.md
  doc/loggingAndErrorReporting.md
  doc/xmlConfigFile.md
Labels: documentation

#361 Ensure that environment variables are loaded before resolving configurations
  src/Core/WinSWCore/ServiceDescriptor.cs
Labels: bug

#474 Document special accounts and the default domain
  doc/xmlConfigFile.md
Labels: documentation

#480 Migrate the release flow to https://ci.appveyor.com/project/winsw/winsw-release/
  DEVELOPER.md
Labels: skip-changelog

#483 Feature/eliminate newlines
  src/Core/ServiceWrapper/Main.cs
Labels: enhancement

#486 Remove v1 from README
  README.md
Labels: documentation

#477 Set up CI with Azure Pipelines
  DEVELOPER.md
  eng/build.yml
  eng/release.yml
  eng/template.yml
Labels: build-flow

#494 Use variable group in pipelines
  eng/build.yml
  eng/release.yml
Labels: build-flow

#496 Skip the failing test
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
Labels: tests

#495 Fix versioning of WinSW builds
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/WinSWCore/WinSWCore.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
  src/Test/winswTests/winswTests.csproj
Labels: bug, build-flow

#491 Enable system default TLS versions when targeting .NET Framework 4.6.1
  src/Core/WinSWCore/Download.cs
Labels: enhancement

#499 Disable PR trigger in release builds
  eng/release.yml
Labels: build-flow

#498 Enable strong cryptography when running .NET 2.0 and 4.0 binaries on .NET Framework 4.6
  src/Core/WinSWCore/Download.cs
Labels: enhancement

#371 Increase code coverage
  src/Core/WinSWCore/Download.cs
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/DownloadTest.cs
  src/Test/winswTests/MainTest.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/CLITestHelper.cs
  src/Test/winswTests/Util/ConfigXmlBuilder.cs
  src/Test/winswTests/Util/ExceptionHelper.cs
  src/Test/winswTests/Util/ServiceDescriptorAssert.cs
  src/Test/winswTests/winswTests.csproj
Labels: tests

#502 Always set process priority if specified
  src/Core/WinSWCore/Util/ProcessHelper.cs
Labels: bug

#505 Skip the failing process helper test
  src/Test/winswTests/Util/ProcessHelperTest.cs
Labels: tests

#506 Remove dead codes
  Directory.Build.targets
  src/Core/WinSWCore/Util/ProcessHelper.cs
  src/Core/WinSWCore/WinSWCore.csproj
  src/Core/WinSWCore/Wmi.cs
Labels: internal

#512 Remove offline mode section from installation guide
  doc/installation.md
Labels: documentation

#478 Remove strong name signing
  .gitignore
  Directory.Build.props
  generate-key.ps1
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/WinSWCore/WinSWCore.csproj
  src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
Labels: build-flow

#507 Update badges on README
  README.md
Labels: documentation

#511 Fix default working directory on .NET Core
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
Labels: bug

#500 Cleanup and restructure the README page
  README.md
Labels: documentation

#514 Revise the installation guide
  doc/exeConfigFile.md
  doc/installation.md
Labels: documentation

#515 Ensure event source is registered during installation
  src/Core/ServiceWrapper/Main.cs
Labels: bug

#457 Prompt for elevation
  README.md
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/winsw.csproj
  src/Core/WinSWCore/Native/Advapi32.cs
  src/Core/WinSWCore/Native/Errors.cs
  src/Core/WinSWCore/Native/Kernel32.cs
  src/Core/WinSWCore/Util/SigIntHelper.cs
Labels: new-feature

#410 Remove app manifest file
  src/Core/ServiceWrapper/manifest.xml
  src/Core/ServiceWrapper/winsw.csproj
Labels: internal

#516 Remove content about renaming running executables
  doc/deferredFileOperations.md
Labels: documentation

#521 Remove locale from docs.ms link
  doc/xmlConfigFile.md
Labels: documentation, skip-changelog

#522 Warn about broken settings
  doc/loggingAndErrorReporting.md
Labels: documentation

#524 Merge build pipelines
  eng/build.yml
  eng/release.yml
  eng/template.yml
Labels: build-flow

#525 Stop building the project on Appveyor, remove the build definition
  appveyor.yml
Labels: build-flow

#527 Note about the "incremental download" feature
  doc/xmlConfigFile.md
Labels: documentation
