Repository winsw/winsw, pull requests merged in 2020-06, with the labels that each got.

#542 ...
  CONTRIBUTING.md
  doc/developer/projectStructure.md
Labels: documentation, skip-changelog

#535 Decouple CLI and service
  src/Core/ServiceWrapper/Main.cs
  src/Core/ServiceWrapper/Program.cs
  src/Core/ServiceWrapper/WrapperService.cs
  src/Test/winswTests/Util/CLITestHelper.cs
  src/Test/winswTests/Util/TestHelper.cs
Labels: internal

#548 Fix outdated tag
  doc/extensions/runawayProcessKiller.md
  doc/extensions/sharedDirectoryMapper.md
  doc/installation.md
  doc/loggingAndErrorReporting.md
  doc/xmlConfigFile.md
  examples/sample-allOptions.xml
  src/Core/WinSWCore/LogAppenders.cs
  src/Plugins/RunawayProcessKiller/sampleConfig.xml
  src/Plugins/SharedDirectoryMapper/sampleConfig.xml
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/CLITestHelper.cs
Labels: documentation

#550 Add NuGet.config
  eng/build.yml
  src/NuGet.config
Labels: build-flow

#553 Improve signal-related logging
  src/Core/WinSWCore/Native/Errors.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
  src/Core/WinSWCore/Util/SigIntHelper.cs
  src/Core/WinSWCore/Util/SignalHelper.cs
Labels: enhancement

#554 WinSW v3 test plan
  eng/build.yml
Labels: build-flow

#558 Add a Dependabot configuration
  .github/dependabot.yml
Labels: internal
