Repository winsw/winsw, pull requests merged in 2020-07, with the labels that each got.

#557 Allow prompting for credentials
  src/Core/ServiceWrapper/Program.cs
  src/Core/WinSWCore/Native/CredentialApis.cs
  src/Core/WinSWCore/Native/Errors.cs
  src/Core/WinSWCore/Native/Libraries.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
Labels: new-feature

#572 Set up code coverage
  .config/dotnet-tools.json
  eng/build.yml
Labels: build-flow

#487 Remove <stopparentprocessfirst> setting and fix process termination
  doc/extensions/runawayProcessKiller.md
  doc/xmlConfigFile.md
  examples/sample-allOptions.xml
  src/Core/ServiceWrapper/WrapperService.cs
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/Util/ProcessHelper.cs
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Plugins/RunawayProcessKiller/sampleConfig.xml
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/ConfigXmlBuilder.cs
Labels: bug

#372 Avoid setting current process environment variables
  src/Core/WinSWCore/Util/ProcessHelper.cs
  src/Test/winswTests/Util/FilesystemTestHelper.cs
  src/Test/winswTests/Util/ProcessHelperTest.cs
Labels: internal

#406 Rename docs for SEO
  CONTRIBUTING.md
  README.md
  WinSW.nuspec
  doc/exeConfigFile.md
  doc/puppetWinSW.md
  docs/deferred-file-operations.md
  docs/developer/project-structure.md
  docs/exe-config-file.md
  docs/extensions/extensions.md
  docs/extensions/runaway-process-killer.md
  docs/extensions/shared-directory-mapper.md
  docs/installation.md
  docs/logging-and-error-reporting.md
  docs/selfRestartingService.md
  docs/xml-config-file.md
  samples/sample-complete.xml
  samples/sample-minimal.xml
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/winsw.sln
Labels: documentation

#584 Check start time of possible child processes
  src/Core/WinSWCore/Util/ProcessHelper.cs
Labels: bug

#585 Migrate tests to xUnit
  src/Test/winswTests/Attributes/ElevatedFactAttribute.cs
  src/Test/winswTests/Configuration/ExamplesTest.cs
  src/Test/winswTests/DownloadConfigTests.cs
  src/Test/winswTests/DownloadTests.cs
  src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
  src/Test/winswTests/Extensions/SharedDirectoryMapperConfigTest.cs
  src/Test/winswTests/Extensions/SharedDirectoryMapperTests.cs
  src/Test/winswTests/MainTest.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/Util/AsyncAssert.cs
  src/Test/winswTests/Util/CLITestHelper.cs
  src/Test/winswTests/Util/ProcessHelperTest.cs
  src/Test/winswTests/Util/ServiceDescriptorAssert.cs
  src/Test/winswTests/Util/TestHelper.cs
  src/Test/winswTests/winswTests.csproj
Labels: internal, tests

#583 Disable Codedov commit status
  .github/codecov.yml
Labels: internal

#588 Don't print to console
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/DownloadConfigTests.cs
  src/WinSW.Tests/Extensions/RunawayProcessKillerTest.cs
  src/WinSW.Tests/ServiceDescriptorTests.cs
  src/WinSW.Tests/Util/ConfigXmlBuilder.cs
  src/WinSW.Tests/Util/FilesystemTestHelper.cs
Labels: tests

#581 Improve exception logging
  src/WinSW.Core/CommandException.cs
  src/WinSW.Core/Native/Security.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/Throw.cs
  src/WinSW/Program.cs
Labels: enhancement

#592 Add .gitattributes
  .gitattributes
Labels: internal

#591 Upgrade build flows
  eng/build.yml
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/WinSW.csproj
Labels: build-flow

#543 YAML Configurations Support (GSoC - 2020)
  src/Core/ServiceWrapper/Program.cs
  src/Core/ServiceWrapper/WrapperService.cs
  src/Core/WinSWCore/Configuration/DefaultSettings.cs
  src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
  src/Core/WinSWCore/Configuration/Log.cs
  src/Core/WinSWCore/Configuration/ServiceAccount.cs
  src/Core/WinSWCore/Configuration/YamlConfiguration.cs
  src/Core/WinSWCore/Extensions/AbstractWinSWExtension.cs
  src/Core/WinSWCore/Extensions/IWinSWExtension.cs
  src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/ServiceDescriptorYaml.cs
  src/Core/WinSWCore/WinSWCore.csproj
  src/NuGet.Config
  src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
  src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
  src/Test/winswTests/ServiceDescriptorTests.cs
  src/Test/winswTests/ServiceDescriptorYamlTest.cs
  src/Test/winswTests/Util/ServiceDescriptorAssert.cs
Labels: enhancement, gsoc

#422 Replace thread with event
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW/WrapperService.cs
Labels: internal

#421 Publish self-contained archives
  eng/build.yml
  src/WinSW/WinSW.csproj
Labels: packaging

#423 Replace threads with tasks
  src/WinSW.Core/LogAppenders.cs
Labels: internal

#597 Fix termination
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW/WrapperService.cs
Labels: bug

#595 Add `prestart`/`poststart`/`prestop`/`poststop` settings
  src/WinSW.Core/Configuration/SettingNames.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/ServiceDescriptorTests.cs
  src/WinSW/WinSW.csproj
  src/WinSW/WrapperService.cs
Labels: new-feature

#485 Redirect event logging
  src/WinSW/WrapperService.cs
Labels: bug

#598 Catch all exceptions
  src/WinSW.Core/FormatExtensions.cs
  src/WinSW.Core/LogAppenders.cs
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW/Logging/WrapperServiceEventLogProvider.cs
  src/WinSW/WrapperService.cs
Labels: bug

#601 Rename to Nuget.Config
  src/NuGet.Config
Labels: internal

#593 Delete NuGet.config
  src/NuGet.config
Labels: internal

#590 Fix file permission and line ending issues
  src/Core/WinSWCore/Download.cs
  src/Core/WinSWCore/DynamicProxy.cs
  src/Core/WinSWCore/LogAppenders.cs
  src/Core/WinSWCore/Native/Kernel32.cs
  src/Core/WinSWCore/PeriodicRollingCalendar.cs
  src/Core/WinSWCore/ServiceDescriptor.cs
  src/Core/WinSWCore/Wmi.cs
  src/Core/WinSWCore/WmiSchema.cs
  src/winsw.sln
Labels: internal

#426 Fix the stop logic
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW/WrapperService.cs
Labels: bug

#602 Remove `<waithint>` and `<sleeptime>`
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Configuration/IWinSWConfiguration.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/ServiceDescriptorTests.cs
  src/WinSW/WrapperService.cs
Labels: removed

#603 Disable undocumented argument concatenation
  src/WinSW/WrapperService.cs
Labels: bug

#607 Add `refresh` command
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW/Program.cs
Labels: new-feature

#589 New command-line interface
  src/WinSW.Core/AssemblyInfo.cs
  src/WinSW.Core/Native/Credentials.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/Attributes/ElevatedFactAttribute.cs
  src/WinSW.Tests/MainTest.cs
  src/WinSW.Tests/Util/CommandLineTestHelper.cs
  src/WinSW/Program.cs
  src/WinSW/ServiceControllerExtension.cs
  src/WinSW/UserException.cs
  src/WinSW/WinSW.csproj
Labels: new-feature

#594 Revise docs for 3.0.0-alpha.2
  LICENSE.txt
  README.md
  WinSW.nuspec
  docs/cli-commands.md
  docs/migrate-to-3-x.md
  docs/xml-config-file.md
  samples/sample-complete.xml
  samples/sample-minimal.xml
  src/WinSW.Tests/MainTest.cs
  src/WinSW/WinSW.csproj
Labels: documentation

#609 Make `<name>` and `<description>` optional
  samples/sample-complete.xml
  samples/sample-minimal.xml
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/Configuration/ExamplesTest.cs
  src/WinSW.Tests/Util/ServiceDescriptorAssert.cs
  src/WinSW/Program.cs
Labels: enhancement

#610 Remove `<*argument>`
  docs/xml-config-file.md
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/ServiceDescriptorTests.cs
Labels: removed

#611 Leave STDIN open
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW/WrapperService.cs
Labels: bug

#613 Make `<delayedAutoStart>`/`<beeponshutdown>`/`<interactive>` a boolean
  samples/sample-complete.xml
  src/WinSW.Core/Native/ServiceApis.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/Util/ConfigXmlBuilder.cs
Labels: enhancement

#614 Preshutdown support
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Native/Service.cs
  src/WinSW.Core/NullableAttributes.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Core/Util/ProcessHelper.cs
  src/WinSW/Logging/IServiceEventLog.cs
  src/WinSW/Logging/IServiceEventLogProvider.cs
  src/WinSW/Logging/ServiceEventLogAppender.cs
  src/WinSW/Logging/WrapperServiceEventLogProvider.cs
  src/WinSW/NullableAttributes.cs
  src/WinSW/Program.cs
  src/WinSW/WrapperService.cs
Labels: new-feature

#616 Set a default working directory for the wrapper
  src/WinSW.Core/Configuration/DefaultSettings.cs
  src/WinSW.Core/Configuration/IWinSWConfiguration.cs
  src/WinSW.Core/ServiceDescriptor.cs
  src/WinSW.Tests/Util/ServiceDescriptorAssert.cs
  src/WinSW/WrapperService.cs
Labels: enhancement
