Repository winsw/winsw, pull requests merged in 2021-08, with the labels that each got.

#808 Tiny correction of a typo and some punctuations
  samples/complete.xml
Labels: documentation

#807 Upgrade to .NET 6
  .config/dotnet-tools.json
  Directory.Build.props
  Directory.Build.targets
  eng/build.yml
  src/WinSW.Core/Download.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/WinSW.csproj
Labels: build-flow

#853 Fix download exceptions when ignoring errors
  src/WinSW.Core/Download.cs
  src/WinSW.Core/WrapperService.cs
  src/WinSW.Tests/DownloadTests.cs
Labels: bug

#854 Fix download exceptions when ignoring errors
  src/WinSW.Core/Download.cs
  src/WinSW.Tests/DownloadTests.cs
  src/WinSW/WrapperService.cs
Labels: bug
