Repository winsw/winsw, pull requests merged in 2023-01, with the labels that each got.

#999 Fix build pipelines
  eng/build.yml
Labels: build-flow

#1001 Upgrade to .NET 7
  eng/build.yml
  src/WinSW.Core/AssemblyInfo.cs
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Core/WrapperService.cs
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tasks/Trim.cs
  src/WinSW.Tasks/WinSW.Tasks.csproj
  src/WinSW.Tests/CommandLineTests.cs
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/AssemblyInfo.cs
  src/WinSW/CommandExtensions.cs
  src/WinSW/Program.cs
  src/WinSW/WinSW.csproj
Labels: build-flow

#1003 Fix tests
  src/WinSW.Tests/CommandLineTests.cs
  src/WinSW.Tests/NativeMethods.txt
  src/WinSW.Tests/Util/InterProcessCodeCoverageSession.cs
  src/WinSW.Tests/WinSW.Tests.csproj
Labels: skip-changelog

#780 Update serviceaccount field in sample complete.xml
  samples/complete.xml
Labels: documentation

#875 Update xml-config-file.md
  docs/xml-config-file.md
Labels: documentation

#1004 Upgrade to .NET 7
  Directory.Build.targets
  eng/build.yml
  src/WinSW.Core/AssemblyInfo.cs
  src/WinSW.Core/ILLink.Descriptors.xml
  src/WinSW.Core/WinSW.Core.csproj
  src/WinSW.Plugins/WinSW.Plugins.csproj
  src/WinSW.Tests/WinSW.Tests.csproj
  src/WinSW/Properties/AssemblyInfo.cs
  src/WinSW/WinSW.csproj
Labels: build-flow

#1006 Revise docs for 3.0.0-alpha.11
  README.md
Labels: documentation
